1. What is a Python library? Why do we use Python libraries?


A Python library is a collection of modules and functions that extend the capabilities of the Python programming language. Libraries provide reusable code and pre-built functions that can be used to perform specific tasks or solve particular problems. These libraries are designed to simplify the development process by offering a set of functions and tools that programmers can leverage rather than implementing everything from scratch.

Here are some key reasons why we use Python libraries:

1. **Code Reusability:** Libraries encapsulate common functionality, allowing developers to reuse code that has already been written and tested. This promotes a modular and efficient coding style.

2. **Time Efficiency:** By using pre-built functions and modules from libraries, developers can save time and effort. They don't need to reinvent the wheel for common tasks and can focus on the specific requirements of their projects.

3. **Community Contributions:** Python has a large and active community that contributes to the development of various libraries. These community-driven libraries cover a wide range of domains, from web development to data science, machine learning, and more.

4. **Increased Productivity:** Libraries provide high-level abstractions and tools that simplify complex operations. This leads to increased productivity as developers can accomplish tasks with fewer lines of code.

5. **Quality and Reliability:** Established libraries are often well-tested, and their code has been reviewed by a community of developers. This helps ensure the reliability and quality of the code, reducing the likelihood of bugs.

6. **Specialized Functionality:** Many Python libraries are specialized for specific domains, such as NumPy for numerical computing, pandas for data manipulation, Flask for web development, TensorFlow for machine learning, and more. These libraries provide specialized tools tailored to the needs of different applications.

7. **Compatibility:** Libraries are designed to work seamlessly with the Python programming language. They adhere to Python standards, making it easy to integrate and use them in Python projects.



2. What is the difference between Numpy array and List?

NumPy arrays and Python lists are both used to store and manipulate collections of data, but they have several key differences:

1. **Data Type:**
   - **Numpy Array:** All elements in a NumPy array must have the same data type. This allows for more efficient storage and operations on the array.
   - **List:** Python lists can store elements of different data types.

2. **Performance:**
   - **Numpy Array:** NumPy arrays are more memory-efficient and provide better performance for mathematical operations, especially when dealing with large datasets. NumPy is implemented in C and optimized for numerical computations.
   - **List:** Lists are more flexible but may not perform as well as NumPy arrays for numerical operations.

3. **Size Dynamism:**
   - **Numpy Array:** The size of a NumPy array is fixed upon creation. If you need to change the size, a new array must be created.
   - **List:** Lists in Python can dynamically grow or shrink in size.

4. **Functionality:**
   - **Numpy Array:** NumPy provides a wide range of mathematical operations and functions that can be applied directly to arrays. This includes operations like element-wise addition, multiplication, and functions such as mean, sum, etc.
   - **List:** Lists offer more general-purpose functionality but lack the extensive mathematical operations available in NumPy.

5. **Syntax and Usage:**
   - **Numpy Array:** NumPy arrays are created using the `numpy.array()` function. Operations on arrays are typically performed using vectorized syntax, taking advantage of NumPy's built-in functions.
   - **List:** Lists are created using square brackets `[]`. Operations on lists often involve iteration over elements using loops.

6. **Broadcasting:**
   - **Numpy Array:** NumPy supports broadcasting, which allows operations between arrays of different shapes and sizes. It automatically adjusts the shape of smaller arrays to perform element-wise operations.
   - **List:** Lists do not have built-in broadcasting, and operations usually require explicit looping over elements.

7. **Usage:**
   - **Numpy Array:** Ideal for numerical computations, scientific computing, and tasks involving large datasets.
   - **List:** Used for general-purpose tasks and when flexibility in data types or dynamic resizing is required.



3. Find the shape, size and imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Shape
shape = arr.shape

# Size
size = arr.size

# Dimensions
dimensions = arr.ndim

print("Shape:", shape)
print("Size:", size)
print("Dimensions:", dimensions)


Shape: (3, 4)
Size: 12
Dimensions: 2


4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

first_row = arr[0]

print("First Row:", first_row)


First Row: [1 2 3 4]


5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

element = arr[2, 3]

print("Element at the third row and fourth column:", element)


Element at the third row and fourth column: 12


6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

odd_indexed_elements = arr[:, 1::2]

print("Odd-indexed elements:")
print(odd_indexed_elements)


Odd-indexed elements:
[[ 2  4]
 [ 6  8]
 [10 12]]


7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [ ]:
import numpy as np

random_matrix = np.random.rand(3, 3)

print("Random 3x3 matrix:")
print(random_matrix)


Random 3x3 matrix:
[[0.32501981 0.9638235  0.77293528]
 [0.44861877 0.38309262 0.50961471]
 [0.49818034 0.41947111 0.76494948]]


8. Describe the difference between np.random.rand and np.random.randn?

1.np.random.rand: This function generates random numbers from a uniform distribution over the interval [0, 1). It takes dimensions as arguments and returns an array of random values with those dimensions.

Example:

In [ ]:
import numpy as np

random_array = np.random.rand(2, 3)
print(random_array)


[[0.34361953 0.27783594 0.85868636]
 [0.14647962 0.78064387 0.01580302]]


2.np.random.randn: This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1). Like rand, it takes dimensions as arguments and returns an array of random values with those dimensions.

Example:

In [ ]:
import numpy as np

random_array = np.random.randn(2, 3)
print(random_array)


[[-0.07314198  0.61104051 -0.48724036]
 [-0.76186152  0.7134668  -0.138697  ]]


9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Increase dimension by adding a new axis
expanded_array = original_array[:, :, np.newaxis]

# Alternatively, you can use np.expand_dims
# expanded_array = np.expand_dims(original_array, axis=-1)

print("Original Array:")
print(original_array)
print("\nExpanded Array:")
print(expanded_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Expanded Array:
[[[ 1]
  [ 2]
  [ 3]
  [ 4]]

 [[ 5]
  [ 6]
  [ 7]
  [ 8]]

 [[ 9]
  [10]
  [11]
  [12]]]


10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [ ]:
import numpy as np

# Given array
original_array = np.array([[1, 2, 3, 4],
                           [5, 6, 7, 8],
                           [9, 10, 11, 12]])

# Transpose the array
transposed_array = np.transpose(original_array)

# Alternatively, you can use the T attribute
# transposed_array = original_array.T

print("Original Array:")
print(original_array)
print("\nTransposed Array:")
print(transposed_array)


Original Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed Array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1
1 Index wise multiplication.
2 Matix multiplication
3 Add both the matics
4 Subtact matix B from A
5 Divide Matix B by A

In [ ]:
import numpy as np

# Given matrices
A2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# 1. Index-wise multiplication
index_wise_multiplication = A2 * B2

# 2. Matrix multiplication
matrix_multiplication = np.matmul(A2, B2.transpose())  # Assuming you want to multiply A2 by the transpose of B2

# 3. Matrix addition
matrix_addition = A2 + B2

# 4. Matrix subtraction (subtracting B2 from A2)
matrix_subtraction = A2 - B2

# 5. Element-wise division of B2 by A2
matrix_division = np.divide(B2, A2)

# Display results
print("1. Index-wise Multiplication:")
print(index_wise_multiplication)

print("\n2. Matrix Multiplication:")
print(matrix_multiplication)

print("\n3. Matrix Addition:")
print(matrix_addition)

print("\n4. Matrix Subtraction:")
print(matrix_subtraction)

print("\n5. Element-wise Division of B2 by A2:")
print(matrix_division)


1. Index-wise Multiplication:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

2. Matrix Multiplication:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

3. Matrix Addition:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

4. Matrix Subtraction:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

5. Element-wise Division of B2 by A2:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


12. Which function in Numpy can be used to swap the byte order of an array?

In [ ]:
import numpy as np

# Create an array with a specific byte order (little-endian in this case)
original_array = np.array([1, 2, 3, 4], dtype=np.int32)

# Swap the byte order using byteswap
swapped_array = original_array.byteswap()

# Display the original and swapped arrays
print("Original Array:", original_array)
print("Swapped Array:", swapped_array)


Original Array: [1 2 3 4]
Swapped Array: [16777216 33554432 50331648 67108864]


13. What is the significance of the np.linalg.inv function?

The `np.linalg.inv` function in NumPy is used to compute the (multiplicative) inverse of a square matrix. In linear algebra, the inverse of a matrix A is denoted as A^(-1), and it has the property that when multiplied by the original matrix A, the result is the identity matrix.

The significance of `np.linalg.inv` lies in its application to solve systems of linear equations and other mathematical problems. Here are some key points:

1. **Solving Linear Equations:** Given a system of linear equations in the form Ax = B, where A is a square matrix of coefficients, x is the column vector of variables, and B is the column vector on the right-hand side, you can find the solution by computing x = A^(-1) * B.

2. **Matrix Equations:** It is used in solving matrix equations of the form AX = B, where A, X, and B are matrices. If you know A and B, you can find X by multiplying both sides of the equation by A^(-1): X = A^(-1) * B.

3. **Eigenvalue Problems:** In some cases, the inverse of a matrix is used in the context of eigenvalue problems and diagonalization of matrices.



14. What does the np.reshape function do, and how is it used?

The np.reshape function in NumPy is used to change the shape of an array without changing its data. It allows you to reorganize the elements of an array to fit a specified shape, provided that the total number of elements remains constant.

Here's the general syntax of np.reshape:

numpy.reshape(a, newshape, order='C')

* a: The input array that you want to reshape.
* newshape: The new shape you want for the array. It can be specified as an integer (if the array is one-dimensional) or as a tuple of integers representing the new shape.
* order: (Optional) Specifies the order in which elements are read from the original array for placement in the reshaped array. It can be 'C' (row-major, default) or 'F' (column-major).

Here are some examples to illustrate how np.reshape is used:

In [ ]:
import numpy as np

# Example 1: Reshaping a 1D array to a 2D array
arr1d = np.array([1, 2, 3, 4, 5, 6])
arr2d = np.reshape(arr1d, (2, 3))
print(arr2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Example 2: Reshaping a 2D array to a 1D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr1d = np.reshape(arr2d, 6)
print(arr1d)
# Output: [1 2 3 4 5 6]

# Example 3: Reshaping with automatic inference of one dimension
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = np.reshape(arr, (2, -1))  # -1 means infer the size of the remaining dimension
print(reshaped_arr)
# Output:
# [[1 2 3]
#  [4 5 6]]


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


15. What is broadcasting in Numpy?

Broadcasting in NumPy is a mechanism that allows NumPy to perform operations on arrays of different shapes and sizes. In broadcasting, NumPy automatically adjusts the dimensions of input arrays to perform element-wise operations, even if their shapes are not identical.

The key concept behind broadcasting is that when operating on two arrays, NumPy compares their shapes element-wise, starting from the trailing dimensions. It then performs the operation if:

1.The dimensions are equal.
2.One of the dimensions is 1.

NumPy will automatically replicate or "broadcast" the smaller-sized array along the missing dimensions to make the shapes compatible for element-wise operations.

Here's a simple example to illustrate broadcasting:

In [ ]:
import numpy as np

# Example 1: Broadcasting with a scalar
arr = np.array([1, 2, 3])
result = arr + 5  # Broadcasting scalar 5 to the array
print(result)
# Output: [6 7 8]

# Example 2: Broadcasting with two arrays of different shapes
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2  # Broadcasting arr2 to arr1
print(result)
# Output:
# [[11 22 33]
#  [14 25 36]]


[6 7 8]
[[11 22 33]
 [14 25 36]]
